INSERT INTO books (title, volume, edition, place_of_publication, year_of_publication) 
VALUES
('Algorytmy', NULL, 4, 'Gliwice', 2012),
('Architektura systemów zarządzania przedsiębiorstwem. Wzorce projektowe', NULL, NULL, 'Gliwice', 2005),
('Enterprise JavaBeans 3.0', NULL, NULL, 'Gliwice', 2007),
('Enterprise JavaBeans', NULL, NULL, 'Gliwice', 2003),
('J2EE. Podstawy programowania aplikacji korporacyjnych', NULL, NULL, 'Gliwice', 2006),
('J2EE. Stosowanie wzorców projektowych', NULL, NULL, 'Gliwice', 2004),
('J2EE. Wzorce projektowe', NULL, 2, 'Gliwice', 2004),
('Java 2 dla każdego', NULL, NULL, 'Gliwice', 2001),
('Java EE 6. Leksykon kieszonkowy', NULL, NULL, 'Gliwice', 2013),
('Java EE 6. Przewodnik', NULL, 4, 'Gliwice', 2012),
('Java EE 6. Zaawansowany przewodnik', NULL, 4, 'Gliwice', 2013),
('Java Servlet i JavaServer Pages', 1, 2, 'Gliwice', 2006),
('Java Servlet i JavaServer Pages', 2, 2, 'Gliwice', 2009),
('Java. Podstawy', 1, 8, 'Gliwice', 2008),
('Java. Praktyczne narzędzia', NULL, NULL, 'Gliwice', 2009),
('Java. Techniki zaawansowane', 2, 8, 'Gliwice', 2009),
('JavaScript. Programowanie obiektowe', NULL, NULL, 'Gliwice', 2010),
('JavaServer Faces', NULL, 3, 'Gliwice', 2011),
('JDBC. Leksykon kieszonkowy', NULL, NULL, 'Gliwice', 2003),
('Linux. Niezbędnik programisty', NULL, NULL, 'Gliwice', 2009),
('Refaktoryzacja do wzorców projektowych', NULL, NULL, 'Gliwice', 2005),
('Refaktoryzacja. Ulepszanie struktury istniejącego kodu', NULL, NULL, 'Gliwice', 2011),
('Sieci komputerowe', NULL, 5, 'Gliwice', 2012),
('SQL dla każdego', NULL, NULL, 'Gliwice', 2001),
('SQL. Leksykon kieszonkowy', NULL, 2, 'Gliwice', 2011),
('Systemy baz danych. Kompletny przewodnik', NULL, NULL, 'Gliwice', 2011),
('UML w kropelce. Wersja 2.0', NULL, NULL, 'Warszawa', 2005),
('Wzorce projektowe. Elementy oprogramowania obiektowego wielokrotnego użytku', NULL, NULL, 'Gliwice', 2010),
('XML. Leksykon kieszonkowy', NULL, NULL, 'Gliwice', 2000);
