INSERT INTO merchandise_pl (name) 
VALUES
('jabłko'),
('gruszka'),
('pomarańcza'),
('winogrono'),
('cytryna'),
('ziemniak'),
('kapusta'),
('marchew'),
('cebula'),
('śliwka'),
('wiśnia'),
('pieczarka'),
('pomidor'),
('ogórek'),
('banan'),
('orzech ziemny'),
('orzech włoski'),
('bochenek chleba'),
('bochenek chleba razowego'),
('mufinka'),
('bułka'),
('arbuz'),
('kokos'),
('karton mleka 500ml'),
('butelka mleka 1l'),
('rzodkiew'),
('maniok');
